### ISSUE TITLE
the xray loss is nan

### ISSUE THREAD

**Issue by niyunsheng** [neverUseThisName/Face-X-Ray#6]
is there any body who want to reproduce the paper？

I have implemented all the parts and experiments, the strange thing is that the loss of this xray is infinity, I don’t know what the problem is

can we talk about this paper ?
I have done all the experiments, but if the loss add xray, it will be nan!

**Comment by xuyingzhongguo** [comment]
Hello, do you mind sharing you code so that we could discuss?

**Comment by niyunsheng** [comment]
It's been too long for me to stop doing this.
